name: Create release
on:
  push:
    tags:
      - 'v*.*.*'
env:
  GO111MODULE: on
  GOARCH: amd64
  GOOS: linux
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Debug
      run: |
        pwd
        ls -l
        env

    - name: Build the release binary
      run: go build -ldflags '-s -w' -trimpath
      env:
        CGO_ENABLED: 0

    - name: Archive the artifacts
      run: tar -czf artifacts.tar.gz LICENSE README golang-actions-practice

    - name: Get version
      id: get_version
      run: |
        VERSION=$(basename ${{ github.ref }})
        echo ::set-output name=version::${VERSION}
        echo ::set-output name=prerelease::$(case ${VERSION} in *-*) echo true ;; *) echo false; esac)

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: ${{ steps.get_version.outputs.prerelease }}

    - name: Upload the release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts.tar.gz
        asset_name: golang-actions-practice_${{ steps.get_version.outputs.version }}_${{ env.GOOS }}_${{ env.GOARCH }}.tar.gz
        asset_content_type: application/gzip
